# Content:
 1. [Data types](#1.-Data-types)
 2. [String manipulations: Slicing vs. Splitting](#2.-String-manipulations:-Slicing-vs.-Splitting)
 3. [List](#3.-List)
 4. [Concatenation vs. appending](#4.-Concatenation-vs.-appending)
 5. [For loop](#5.-For-loop)
 6. [While loop](#6.-While-loop)
 7. [Break vs. continue](#7.-Break-vs.-continue)
 8. [Function](#8.-Function)
 9. [Modules](#9.-Modules)
    >[9.1 math](#9.1-math)
    >[9.2 cmath](#9.2-cmath)
    >[9.3 numpy](#9.3-numpy)
    >>[9.3.1 1D array](#9.3.1-1D-array)
    >>[9.3.2 2D array](#9.3.2-2D-array)
    >>[9.3.3 dot, inner and outer products](#9.3.3-dot,-inner-and-outer-products)
 10. [Input/Output](#10.-Input/Output)
     >[10.1 Formatted output](#10.1-Formatted-output)
     >[10.2 Read/Write](#10.2-Read/Write)

## 1. Data types


- integer
- float
- complex
- string

In [1]:
a=1
type(a)

int

In [2]:
a=1.0
type(a)

float

In [3]:
a=complex(1,0)
type(a)

complex

In [4]:
a='1'

In [5]:
type(a)

str

Note: We use single quotes for strings

## 2. String manipulations: Slicing vs. Splitting

In [6]:
str='May the force be with you'

Slicing

In [7]:
str[0]

'M'

In [8]:
str[0:1]

'M'

In [9]:
str[0:5]

'May t'

Splitting

In [10]:
str.split()

['May', 'the', 'force', 'be', 'with', 'you']

Splitting and slicing

In [11]:
str.split()[0:3]

['May', 'the', 'force']

Other delimiters instead of space

In [12]:
str='1,2,3,4'
str.split(',')

['1', '2', '3', '4']

In [13]:
str.split(',')[0:2]

['1', '2']

In [14]:
seq='AATCCGCTACGCTGAATCCGACTACA'
sub_seqs=seq.split('A')
print(sub_seqs)             # Split between successive adenines

['', '', 'TCCGCT', 'CGCTG', '', 'TCCG', 'CT', 'C', '']


In [15]:
type(sub_seqs)

list

In [16]:
N=len(sub_seqs)
print(N)

9


In [17]:
for i in range(0,N):
    print(i,sub_seqs[i])    # NOTE: 4 empty spaces for intendation

0 
1 
2 TCCGCT
3 CGCTG
4 
5 TCCG
6 CT
7 C
8 


## 3. List

We have seen in one of the statements above that splitting a string returns a list. A list is useful object to collect  data.

In [18]:
seq='AATCCGCTACGCTGAATCCGACTACA'
sub_seqs=seq.split('A')
type(sub_seqs)

list

In [19]:
list_A=[1,2,3]
type(list_A)

list

In [20]:
type(list_A[0:1])

list

In [21]:
type(list_A[0])

int

In [22]:
print(type(list_A[0]))

<class 'int'>


In [23]:
list_B=[1,'one']      # NOTE: contains objects of different types
print(type(list_B[0]),type(list_B[1]))

<class 'int'> <class 'str'>


In [24]:
len(list_B)

2

Shallow copy vs. deep copy

In [25]:
A=[1,2,3,4]
print("List A is:", A)
B=A[0:3]                    # Ignoring [0:3] means all elements are used
print("List B is:", B)
B[2]=7
print("List A is:", A)
print("List B is:", B)

List A is: [1, 2, 3, 4]
List B is: [1, 2, 3]
List A is: [1, 2, 3, 4]
List B is: [1, 2, 7]


Note that when B is changed A is also affected because the statement B=A does not 'copy' but only 'links' B to A. In order to copy a list to another independent one, one has to deep copy as shown below.

In [26]:
A=[1,2,3,4]
print("List A is:", A)
B=A.copy()[0:3]    # Deep copy, ignoring [0:3] means all elements are used
print("List B is:", B)
B[2]=7
print("List A is:", A)
print("List B is:", B)

List A is: [1, 2, 3, 4]
List B is: [1, 2, 3]
List A is: [1, 2, 3, 4]
List B is: [1, 2, 7]


## 4. Concatenation vs. appending

In [27]:
str1='What'
str2='is'
str3='life?'
print(str1+str2+str3)   # Concatenation of strings
print(str1+' '+str2+' '+str3)

Whatislife?
What is life?


In [28]:
str4=[str1,str2]
str5=[str3]
str4+str5              # Append elements to a list 

['What', 'is', 'life?']

## 5. For loop

In [29]:
N=5

In [30]:
for i in range(N):   # default offset (initial index) is 0, final index is N-1
    print(i)

0
1
2
3
4


In [31]:
for i in range(0,N):
    print(i)

0
1
2
3
4


In [32]:
for i in range(3,N):
    print(i)

3
4


In [33]:
for i in range(0,N,2):  # initial index = 0, final index = N, stride/step = 2
    print(i)

0
2
4


In [34]:
for i in range(N,0,-1):   # runs until 0+1
    print(i)

5
4
3
2
1


In [35]:
for i in [1,1,2,3,5,8]:  # instead of range, one can use a list
    print(i)

1
1
2
3
5
8


## 6. While loop

In [36]:
i=0
while i<5:
    print(i)
    i=i+1

0
1
2
3
4


## 7. Break vs. continue

In [37]:
for i in range(0,8):
    if i == 5:       # same as if (i == 5):
        continue     # when i takes the value 5, the loop is skipped
    print(i)

0
1
2
3
4
6
7


In [38]:
for i in range(0,8):
    if i == 5:    # same as if (i == 5):
        break     # when i takes the value 5, the loop is terminated
    print(i)

0
1
2
3
4


In [39]:
for i in range(1,8):
    if i%2 != 0:     # same as if (if i%2 != 0):
        continue     # when i is odd skip
    print(i)

2
4
6


## 8. Function

If part of your code performing a task is repeated multiple times, it is best to define that part of the code as a function. Here is how you can make your own function. This function will determine if an input data is an integer or not. The output will be 'true' if the data is an integer and 'false' is the data is not an integer.

In [40]:
def is_int(x):
    '''
    Takes an object as input and returns a boolean data as output.
    '''
    is_int=False       # Assign False at the beginning 
    data_1=type(x)
    data_2=type(1)
    if data_1==data_2:
        is_int=True
    return (is_int)

In [41]:
is_int(10)

True

In [42]:
type(is_int(10))

bool

In [43]:
help(is_int)

Help on function is_int in module __main__:

is_int(x)
    Takes an object as input and returns a boolean data as output.



Print the doc string of a function to know more about the function.

In [44]:
print(is_int.__doc__) 


    Takes an object as input and returns a boolean data as output.
    


## 9. Modules

One of the great advantages of using Python is the availability of a number of packages and modules that can be imported in our codes. 

### 9.1 math

In [2]:
import math
#dir(math)      # uncomment and see

In [46]:
help(math.erf)

Help on built-in function erf in module math:

erf(...)
    erf(x)
    
    Error function at x.



In [47]:
print(math.erf.__doc__)

erf(x)

Error function at x.


In [48]:
math.sqrt(2)

1.4142135623730951

In [49]:
import math as m
m.sqrt(2)

1.4142135623730951

In [50]:
from math import sqrt
sqrt(2)

1.4142135623730951

### 9.2 cmath

In [51]:
import cmath
# dir(cmath)   # uncomment and see

In [52]:
cmath.sin(math.pi/2)

(1+0j)

### 9.3 numpy

One of the most useful modules for this course is numpy. As a first application, we will use numpy to create 'arrays'. 

In [53]:
import numpy
#dir(numpy)   # uncomment and see

#### 9.3.1 1D array

In [54]:
import numpy as np
a=np.array([1.0,2.0])   # Note that [1.0,2.0] is a list
print(a)
print(type(a))

[ 1.  2.]
<class 'numpy.ndarray'>


In [55]:
b=[1.0,2.0]  # a list
a=np.array(b)
print(a)
print(type(a))

[ 1.  2.]
<class 'numpy.ndarray'>


In [56]:
a1=np.array(b,int)
print(a1)
a2=np.array(b,float)
print(a2)
a3=np.array(b,complex)
print(a3)

[1 2]
[ 1.  2.]
[ 1.+0.j  2.+0.j]


#### 9.3.2 2D array

In [57]:
A=np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


#### 9.3.3 dot, inner and outer products 

![board%20work%20-1.jpg](boardwork/board%20work%20-1.jpg)
![board%20work%20-2.jpg](boardwork/board%20work%20-2.jpg)

In [58]:
A=np.array([[1,2],[3,2]])
B=np.array([[1,1],[2,2]])
x=np.array([7,3])
y=np.array([2,1])

In [59]:
print(np.dot(A,B))

[[5 5]
 [7 7]]


In [60]:
print(np.dot(A,x))

[13 27]


In [61]:
print(np.dot(x,y))

17


In [62]:
print(np.inner(A,B))

[[ 3  6]
 [ 5 10]]


In [63]:
print(np.inner(A,x))

[13 27]


In [64]:
print(np.inner(x,y))

17


In [65]:
print(np.outer(A,B))

[[1 1 2 2]
 [2 2 4 4]
 [3 3 6 6]
 [2 2 4 4]]


In [66]:
print(np.outer(A,x))

[[ 7  3]
 [14  6]
 [21  9]
 [14  6]]


In [67]:
print(np.outer(x,y))

[[14  7]
 [ 6  3]]


## 10. Input/Output

In [68]:
a=input('Enter a real number: \n')

Enter a real number: 
1.0


In [69]:
print(type(a), type(eval(a)))

<class 'str'> <class 'float'>


### 10.1 Formatted output 

In [70]:
for i in range(11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [71]:
for i in range(11):
    print('{:5d}'.format(i))   # '{:5d}' means integer of width 5 characters

    0
    1
    2
    3
    4
    5
    6
    7
    8
    9
   10


In [72]:
for i in range(11):
    print('{:05d}'.format(i)) # '{:05d}' means integer of width 5 characters with empty spaces filled with zeroes

00000
00001
00002
00003
00004
00005
00006
00007
00008
00009
00010


In [73]:
for i in range(5):
    print('{:8.3f}{:8.3f}'.format(i,math.sqrt(i))) # floats of 8-character width with 3 characters for fractions

   0.000   0.000
   1.000   1.000
   2.000   1.414
   3.000   1.732
   4.000   2.000


In [74]:
for i in range(5):
    print('{:8.3E}{:8.3E}'.format(i,math.sqrt(i))) # This is desired!

0.000E+000.000E+00
1.000E+001.000E+00
2.000E+001.414E+00
3.000E+001.732E+00
4.000E+002.000E+00


In [75]:
for i in range(5):
    print('{:8.3E} {:8.3E} {:8.3e} {:8.3e}'.format(i,math.sqrt(i),i,math.sqrt(i))) # Exponential format

0.000E+00 0.000E+00 0.000e+00 0.000e+00
1.000E+00 1.000E+00 1.000e+00 1.000e+00
2.000E+00 1.414E+00 2.000e+00 1.414e+00
3.000E+00 1.732E+00 3.000e+00 1.732e+00
4.000E+00 2.000E+00 4.000e+00 2.000e+00


### 10.2 Read/Write

First let's write something in a file

In [76]:
file_001=open('myfile_001.txt','w')
for i in range(10):
    file_001.write('{:8.3E},{:8.3E}'.format(i,math.sqrt(i)))
file_001.close()    

In [77]:
import os
os.getcwd()    # get the current working directory

'/Users/raghurama/Gdrive/tcis/Teaching/2021_NM/prog'

Now check the content of the file 'myfile_001.txt' in the working directory 

In [78]:
file_001=open('myfile_001.txt','w')
for i in range(10):
    file_001.write('{:8.3E},{:8.3E}\n'.format(i,math.sqrt(i)))
file_001.close() 

Now let's read the same file

In [79]:
file_001=open('myfile_001.txt','r')
for line in file_001:
    print(line)
file_001.close() 

0.000E+00,0.000E+00

1.000E+00,1.000E+00

2.000E+00,1.414E+00

3.000E+00,1.732E+00

4.000E+00,2.000E+00

5.000E+00,2.236E+00

6.000E+00,2.449E+00

7.000E+00,2.646E+00

8.000E+00,2.828E+00

9.000E+00,3.000E+00



In [80]:
file_001=open('myfile_001.txt','r')
for line in file_001:
    col_1=line.split(',')[0]
    print(col_1,type(col_1),eval(col_1),type(eval(col_1)))
file_001.close() 

0.000E+00 <class 'str'> 0.0 <class 'float'>
1.000E+00 <class 'str'> 1.0 <class 'float'>
2.000E+00 <class 'str'> 2.0 <class 'float'>
3.000E+00 <class 'str'> 3.0 <class 'float'>
4.000E+00 <class 'str'> 4.0 <class 'float'>
5.000E+00 <class 'str'> 5.0 <class 'float'>
6.000E+00 <class 'str'> 6.0 <class 'float'>
7.000E+00 <class 'str'> 7.0 <class 'float'>
8.000E+00 <class 'str'> 8.0 <class 'float'>
9.000E+00 <class 'str'> 9.0 <class 'float'>
